-- Sample hospital data for MongoDB (this would be inserted via MongoDB shell or application code)
-- Since we're using MongoDB, this SQL file is for reference only
-- The actual data insertion would be done through MongoDB shell or application initialization

-- Sample hospitals data (JSON format for MongoDB):
/*
db.hospitals.insertMany([
  {
    "name": "Apollo Hospitals",
    "address": "21 Greams Lane, Off Greams Road",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "zipCode": "600006",
    "phone": "+91-44-2829-3333",
    "email": "info@apollohospitals.com",
    "website": "https://www.apollohospitals.com",
    "latitude": 13.0827,
    "longitude": 80.2707,
    "type": "general",
    "ownership": "private",
    "bedCount": 1000,
    "emergencyServices": "yes",
    "services": ["Emergency Care", "Surgery", "Cardiology", "Oncology", "Neurology"],
    "specialties": ["Cardiology", "Neurology", "Orthopedics", "Oncology"],
    "operatingHours": "24/7",
    "rating": 4.5,
    "reviewCount": 2500,
    "acceptedInsurances": ["Star Health", "ICICI Lombard", "Bajaj Allianz"],
    "emergencyContact": "+91-44-2829-3333",
    "appointmentContact": "+91-44-2829-3334",
    "imageUrl": "https://images.unsplash.com/photo-1551190822-a9333d879b1f?w=800&h=600&fit=crop",
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "Max Super Speciality Hospital",
    "address": "FC-50, C & D Block, Shalimar Bagh",
    "city": "New Delhi",
    "state": "Delhi",
    "zipCode": "110088",
    "phone": "+91-11-6642-2222",
    "email": "info@maxhealthcare.com",
    "website": "https://www.maxhealthcare.in",
    "latitude": 28.7176,
    "longitude": 77.1636,
    "type": "general",
    "ownership": "private",
    "bedCount": 500,
    "emergencyServices": "yes",
    "services": ["Emergency Care", "Surgery", "Cardiology", "Orthopedics"],
    "specialties": ["Cardiology", "Orthopedics", "Neurology", "Gastroenterology"],
    "operatingHours": "24/7",
    "rating": 4.3,
    "reviewCount": 1800,
    "acceptedInsurances": ["Max Bupa", "Star Health", "HDFC ERGO"],
    "emergencyContact": "+91-11-6642-2222",
    "appointmentContact": "+91-11-6642-2223",
    "imageUrl": "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=800&h=600&fit=crop",
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "Fortis Hospital",
    "address": "Sector 62, Phase-VIII, Mohali",
    "city": "Mohali",
    "state": "Punjab",
    "zipCode": "160062",
    "phone": "+91-172-469-2222",
    "email": "info@fortishealthcare.com",
    "website": "https://www.fortishealthcare.com",
    "latitude": 30.7046,
    "longitude": 76.7179,
    "type": "general",
    "ownership": "private",
    "bedCount": 300,
    "emergencyServices": "yes",
    "services": ["Emergency Care", "Cardiology", "Oncology", "Nephrology"],
    "specialties": ["Cardiology", "Oncology", "Nephrology", "Urology"],
    "operatingHours": "24/7",
    "rating": 4.4,
    "reviewCount": 1500,
    "acceptedInsurances": ["ICICI Lombard", "Bajaj Allianz", "Reliance General"],
    "emergencyContact": "+91-172-469-2222",
    "appointmentContact": "+91-172-469-2223",
    "imageUrl": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&h=600&fit=crop",
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "Manipal Hospitals",
    "address": "98, HAL Airport Road",
    "city": "Bangalore",
    "state": "Karnataka",
    "zipCode": "560017",
    "phone": "+91-80-2502-4444",
    "email": "info@manipalhospitals.com",
    "website": "https://www.manipalhospitals.com",
    "latitude": 12.9600,
    "longitude": 77.6480,
    "type": "general",
    "ownership": "private",
    "bedCount": 600,
    "emergencyServices": "yes",
    "services": ["Emergency Care", "Surgery", "Cardiology", "Neurology"],
    "specialties": ["Cardiology", "Neurology", "Orthopedics", "Gastroenterology"],
    "operatingHours": "24/7",
    "rating": 4.6,
    "reviewCount": 2200,
    "acceptedInsurances": ["Star Health", "Apollo Munich", "HDFC ERGO"],
    "emergencyContact": "+91-80-2502-4444",
    "appointmentContact": "+91-80-2502-4445",
    "imageUrl": "https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=800&h=600&fit=crop",
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "name": "AIIMS Delhi",
    "address": "Ansari Nagar",
    "city": "New Delhi",
    "state": "Delhi",
    "zipCode": "110029",
    "phone": "+91-11-2658-8500",
    "email": "info@aiims.edu",
    "website": "https://www.aiims.edu",
    "latitude": 28.5672,
    "longitude": 77.2100,
    "type": "teaching",
    "ownership": "government",
    "bedCount": 2000,
    "emergencyServices": "yes",
    "services": ["Emergency Care", "Research", "Education", "All Specialties"],
    "specialties": ["All Medical Specialties", "Research", "Education"],
    "operatingHours": "24/7",
    "rating": 4.7,
    "reviewCount": 3500,
    "acceptedInsurances": ["CGHS", "ESI", "Private Insurance"],
    "emergencyContact": "+91-11-2658-8500",
    "appointmentContact": "+91-11-2658-8501",
    "imageUrl": "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=800&h=600&fit=crop",
    "createdAt": new Date(),
    "updatedAt": new Date()
  }
]);
*/
